name: Robo Anti-Hibernacao Streamlit

# Define quando o robô vai rodar
on:
  schedule:
    # Roda automaticamente a cada 2 dias, ao meio-dia
    - cron: "0 12 */2 * *"
  # Permite que você ative o robô manualmente se quiser testar
  workflow_dispatch:

jobs:
  ping_site:
    runs-on: ubuntu-latest
    steps:
      - name: Acessando o App da Helipê
        # O comando 'curl' simula um navegador acessando o seu link
        run: curl -s https://guia52semanas.streamlit.app > /dev/null
      
      - name: Sucesso
        run: echo "O aplicativo foi acessado e continua acordado!"
