name: Robo Anti-Hibernacao Streamlit

on:
  schedule:
    # Roda TODOS OS DIAS ao meio-dia (horário UTC)
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  ping_site:
    runs-on: ubuntu-latest
    steps:
      - name: Acessando o App com disfarce de Google Chrome
        run: curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" -s https://guia52semanas.streamlit.app > /dev/null
      
      - name: Sucesso
        run: echo "Ping enviado com máscara de navegador!"
