[theme]
# Cor principal (Botões, sliders, etc - o seu Verde Sálvia)
primaryColor="#A3B18A"

# Fundo principal do app (Branco)
backgroundColor="#ffffff"

# Fundo secundário (usado em caixas e painéis - coloquei um bege clarinho da Helipê)
secondaryBackgroundColor="#F4F1DE"

# Cor dos textos (Preto)
textColor="#000000"
